//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Weds.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDetail
    {
        public int CandidateAddressId { get; set; }
        public string ResidentAddress { get; set; }
        public string PermenentAddress { get; set; }
        public string CanctactNo1 { get; set; }
        public string CanctactNo2 { get; set; }
        public string EmailId { get; set; }
        //public Nullable<int> CandidateId { get; set; }
    
        //public virtual Canditate_Personal Canditate_Personal { get; set; }
    }
}
