//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Weds.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpectationDetail
    {
        public int CandidateExpectationDetailsId { get; set; }
        public string Height { get; set; }
        public string Surmane { get; set; }
        public string OccupationAndIncome { get; set; }
        public string Education { get; set; }
        public string AgeDiffrence { get; set; }
        public string CitiesArea { get; set; }
        //public Nullable<int> CandidateId { get; set; }
    
        //public virtual Canditate_Personal Canditate_Personal { get; set; }
    }
}
