//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS.Weds.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyDetail
    {
        public int CandidateFamilyDetailsId { get; set; }
        public string Father { get; set; }
        public string Mother { get; set; }
        public string Brothers { get; set; }
        public string Sisters { get; set; }
        public string MarriedBrothers { get; set; }
        public string MarriedSisters { get; set; }
        public string RelativeSurnames { get; set; }
        public string ParentOccupation { get; set; }
        public string FamilyProperty { get; set; }
        public Nullable<int> CandidateId { get; set; }
    
        public virtual Canditate_Personal Canditate_Personal { get; set; }
    }
}
