//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace RTS.Weds.Common
{
     
    public class Canditate_Personal :BaseEntity
    {
           
      
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Gender { get; set; }
        public string MaritialStatus { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BloodGroup { get; set; }
        public string Complexion { get; set; }
        public string FoodHabits { get; set; }
        public string PhysicalDisability { get; set; }
        public string PhysicalDisabilityDetails { get; set; }
        public string specs { get; set; }
        public string lens { get; set; }
        public string CandidateDescription { get; set; }
        public string ImageData { get; set; }
       
    }
}

